### ISSUE TITLE
Virtual Resource: Inconsistent Root Scope

### ISSUE THREAD

**Issue by RichieHowell** [perfectsense/gyro#275]
**Describe the bug**
To avoid using the wrong Resource a bunch and creating confusion around that, I will be nicknaming the 3 different resources in this bug.

When creating a virtual resource (VR), we are able to create resources inside of that virtual resource. When one of the resources(Parent) inside of this VR creates a resource(child), the child does not appear in the root scope. This means that searching for the child in the code that created the parent is impossible, and so you can never be sure if child was created from a previous run. 

**To Reproduce**
The Tester should have access to the ops-test and gyro-brightspot-plugin repositories. The master branch of ops-test has a directory at ops/gyro-root-scope-test. This gyro project requires you to locally build the feature/gcp-disk-directive branch of the gyro-brightspot-plugin repo. Then you just need to gyro up and it should say "Start" and "No Changes".

I recreated this by creating a virtual resource with a single wrapper resource which only uses the info passed to create a AWS VPC. I also put a for loop in this wrapper that prints all the resources found in the root scope. 

**Expected behavior**
I expect that resources created by resources in a virtual resource are in the root scope on future runs of the virtual resource so they can be found. 

**Additional context**

I have been talking to DJ about this issue through private channels so if you need more context and I am unable to give it, he can also be contacted.

**Comment by beetlebugorg** [comment]
Restating your issue to make sure I understand it correctly.

You're using a `@virtual-resource` to encapsulate resources into a reusable component. Inside this `@virtual-resource` you have a custom directive you've written (i.e. `@custom::mydirective`). 

In the implementation of this directive you're attempting to find a resource that was saved to state during a previous execution of Gyro. The issue is that you are unable to find the resource by name  even though it does exist in state:

To put it into code, in the following example, `instance` is `null` even though `myinstance` exists in state? (Note: the name in state would be prefixed with the virtual resource name, so it might be named `name/myinstance`).

```
Resource instance = rootScope.getCurrent().findResource("aws::instance::myinstance");
```

Does this accurately reflect your issue?

**Comment by beetlebugorg** [comment]
Can you test your issue against branch `bugfix/virtual-resource-scope` and report back. I'm not 100% sure this is the right fix but if it fixes your issue that's a start.

**Comment by deepanjan90** [comment]
Worked for me, with the test case that Richie mentioned in this issue.

**Comment by RichieHowell** [comment]
That was the issue and this fixes both the simple case I set up for testing and the more complicated case which actually resulted in an error.
